version: "3.8"

services:
  backend:
    build: .
    container_name: bitbranch-backend
    ports:
      - "5050:5050"
    env_file:
      - .env
    depends_on:
      - mongo
    networks:
      - bitbranch-net

  mongo:
    image: mongo:6
    container_name: bitbranch-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - bitbranch-net

networks:
  bitbranch-net:

volumes:
  mongo-data:
